### ISSUE TITLE
Редмэ читат

### ISSUE THREAD

**Issue by TheMaxMur** [CPTSven/minecraft_mods#1]
В редмэ будэт графа прес качат бегит?
Какэ тута тэлаунчер качат
ээээ
мага нежнее

**Comment by CPTSven** [comment]
1. Прес томбой-тян лизат
2. В могаз за пивом бегит
3. Ослик ебат
4. Из мигаик отчислятца

**Comment by TheMaxMur** [comment]
эээ баля
пачиму ИШАКью закрыль
мага не понил как качат писку из интернета
